#!/bin/bash

# boot a compute node for testing ansible config

FLAVOR=m1.small
imagetype=`echo $0 | cut -d- -f 2`
if [ $imagetype == "centos7" ]
then
  IMAGE="CentOS 7 x86_64-GenericCloud-1503"
elif [ $imagetype == "u1404" ]
then
  IMAGE="trusty-server-14.04-cloudimg-amd64-disk1"
fi
echo imagetype: $imagetype
NAME=$1
OS_KEYNAME=${OS_KEYNAME?Export OS_KEYNAME to select auth key}

nova boot --flavor $FLAVOR \
          --image "$IMAGE" \
          --key-name $OS_KEYNAME \
          --security-groups default \
          $NAME
